# Generated by Django 6.0.4 on 2026-04-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
