# Generated by Django 6.0.1 on 2026-04-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_note_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="user",
        ),
    ]
